### ISSUE TITLE
파일 업로드 실패

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#140]
https://femiwiki.com/w/%ED%8C%8C%EC%9D%BC:%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EB%84%B7%ED%8E%98%EB%AF%B8%EC%82%AC_%EB%8F%84%EC%84%9C_%EB%AA%A8%EC%8A%B5.jpg

```
[51a61e073a4adb533e9ccc9f] 2019-12-21 10:00:31: 종류 "Error"에서 심각한 오류
```

**Comment by lens0021** [comment]
```
[exception] [be94fa8b88dd76487a0b6cd2] /api.php   Error from line 632 of /srv/femiwiki.com/extensions/AWS/s3/AmazonS3FileBackend.php: Call to undefined function wfSuppressWarnings()
#0 /srv/femiwiki.com/includes/libs/filebackend/FileBackendStore.php(994): AmazonS3FileBackend->doGetLocalCopyMulti(array)
#1 /srv/femiwiki.com/includes/libs/filebackend/FileBackendStore.php(972): FileBackendStore->doGetLocalReferenceMulti(array)
#2 /srv/femiwiki.com/includes/libs/filebackend/FileBackend.php(1142): FileBackendStore->getLocalReferenceMulti(array)
#3 /srv/femiwiki.com/includes/filerepo/FileRepo.php(1565): FileBackend->getLocalReference(array)
#4 /srv/femiwiki.com/includes/filerepo/file/File.php(447): FileRepo->getLocalReference(string)
#5 /srv/femiwiki.com/includes/filerepo/file/UnregisteredLocalFile.php(155): File->getLocalRefPath()
#6 /srv/femiwiki.com/includes/filerepo/file/File.php(1392): UnregisteredLocalFile->getMimeType()
#7 /srv/femiwiki.com/includes/filerepo/file/UnregisteredLocalFile.php(120): File->getHandler()
#8 /srv/femiwiki.com/includes/filerepo/file/UnregisteredLocalFile.php(134): UnregisteredLocalFile->cachePageDimensions(integer)
#9 /srv/femiwiki.com/includes/api/ApiQueryImageInfo.php(437): UnregisteredLocalFile->getWidth()
#10 /srv/femiwiki.com/includes/upload/UploadBase.php(2152): ApiQueryImageInfo::getInfo(UploadStashFile, array, ApiResult)
#11 /srv/femiwiki.com/includes/api/ApiUpload.php(113): UploadBase->getImageInfo(ApiResult)
#12 /srv/femiwiki.com/includes/api/ApiMain.php(1598): ApiUpload->execute()
#13 /srv/femiwiki.com/includes/api/ApiMain.php(537): ApiMain->executeAction()
#14 /srv/femiwiki.com/includes/api/ApiMain.php(508): ApiMain->executeActionWithErrorHandling()
#15 /srv/femiwiki.com/api.php(87): ApiMain->execute()
#16 {main}
```

**Comment by lens0021** [comment]
https://github.com/edwardspec/mediawiki-aws-s3 가 [해당 문제를 수정](https://github.com/edwardspec/mediawiki-aws-s3/commit/6c8faed2dc691a23a036a25955ca3c661365fe01)했지만 페미위키에서 사용하는 0.10.0보다 더 최신 안정 릴리스가 없기 때문에 마스터 내지는 특정 트리를 사용하도록 변경하겠습니다.

**Comment by lens0021** [comment]
> https://github.com/edwardspec/mediawiki-aws-s3 가 [해당 문제를 수정](https://github.com/edwardspec/mediawiki-aws-s3/commit/6c8faed2dc691a23a036a25955ca3c661365fe01)했지만 페미위키에서 사용하는 0.10.0보다 더 최신 안정 릴리스가 없기 때문에 마스터 내지는 특정 트리를 사용하도록 변경하겠습니다.

(FYI) 2020년 3월에 0.11.0으로 업그레이드했습니다. [1] [2]

[1] https://github.com/femiwiki/docker-mediawiki/commit/6bb3746272806c5bb2056560615bd628b1f50f41
[2] https://femiwiki.com/index.php?oldid=164033#3.EC.9B.94_28.EC.9D.BC
