### ISSUE TITLE
RESTBase: SiteInfo is unavailable for femiwiki.com

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#151]
시각편집기에서 RESTBase를 경유하는 기능을 사용하려 하면 오류가 나며, 디버그 모드에서 확인하면 다음 경로가 첫 번째 원인으로 나옵니다:

https://femiwiki.com/femiwiki.com/v1/page/html/%EB%8C%80%EB%AC%B8

###### References
- https://www.mediawiki.org/wiki/API:Siteinfo
- https://en.wikipedia.org/api/rest_v1/#/Page%20content/post_page_html__title_

**Comment by lens0021** [comment]
secret.php에 다음 추가함:
```php
$wgVisualEditorAllowLossySwitching = true;
```

**Comment by lens0021** [comment]
로그입니다:
```
{
  "name": "restbase",
  "hostname": "2aad6d1aae46",
  "pid": 28,
  "level": 50,
  "message": "500: server_error",
  "res": {
    "name": "HTTPError",
    "message": "500: server_error",
    "status": 500,
    "body": {
      "type": "server_error",
      "title": "Site info fetch failed.",
      "detail": "SiteInfo is unavailable for femiwiki.com"
    },
    "headers": {
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "GET,HEAD",
      "access-control-allow-headers": "accept, content-type, content-length, cache-control, accept-language, api-user-agent, if-match, if-modified-since, if-none-match, dnt, accept-encoding",
      "access-control-expose-headers": "etag",
      "x-content-type-options": "nosniff",
      "x-frame-options": "SAMEORIGIN",
      "referrer-policy": "origin-when-cross-origin",
      "x-xss-protection": "1; mode=block",
      "content-security-policy": "default-src 'none'; frame-ancestors 'none'",
      "x-content-security-policy": "default-src 'none'; frame-ancestors 'none'",
      "x-webkit-csp": "default-src 'none'; frame-ancestors 'none'",
      "cache-control": "private, max-age=0, s-maxage=0, must-revalidate",
      "x-request-id": "a2b08920-3212-11ea-b6b5-1d1d9e6ef798",
      "server": "2aad6d1aae46"
    }
  },
  "stack": "HTTPError: 500: server_error\n    at _siteInfoCache.(anonymous function)._doRequest.catch (/srv/restbase/node_modules/restbase/sys/action.js:350:23)\n    at tryCatcher (/srv/restbase/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/srv/restbase/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/srv/restbase/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/srv/restbase/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/srv/restbase/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/srv/restbase/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/srv/restbase/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/srv/restbase/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/srv/restbase/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
  "latency": 394,
  "root_req": {
    "method": "get",
    "uri": "/femiwiki.com/v1/page/html/%EB%8C%80%EB%AC%B8",
    "headers": {
      "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
      "x-client-ip": "::ffff:10.0.15.2",
      "x-forwarded-for": "10.255.0.2, ::ffff:10.0.15.2",
      "x-request-id": "a2b08920-3212-11ea-b6b5-1d1d9e6ef798",
      "x-request-class": "internal"
    }
  },
  "request_id": "a2b08920-3212-11ea-b6b5-1d1d9e6ef798",
  "levelPath": "error/request",
  "msg": "500: server_error",
  "time": "2020-01-08T12:30:21.244Z",
  "v": 0
}
```

위 내용 중 `stack` 부분입니다.

```
HTTPError: 500: server_error
    at _siteInfoCache.(anonymous function)._doRequest.catch (/srv/restbase/node_modules/restbase/sys/action.js:350:23)
    at tryCatcher (/srv/restbase/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/restbase/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/srv/restbase/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/srv/restbase/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/srv/restbase/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/srv/restbase/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/srv/restbase/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/srv/restbase/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/srv/restbase/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)m
```

해당 라인입니다:
https://github.com/wikimedia/restbase/blob/bd0072a/sys/action.js#L350-L357

**Comment by lens0021** [comment]
https://femiwiki.com/femiwiki.com/v1/ 로 접속해 보면 스웨거에서 제공하는 API 문서는 잘 나타납니다.

**Comment by lens0021** [comment]
config.yaml 파일의 `MEDIAWIKI_APIS_URI` 등은 정상적으로 잘 치환된 것으로 보입니다.

<details>
<summary>$ docker exec $(docker container ls -qf 'name=mediawiki_restbase') cat config.yaml</summary>

```
# Reference:
#   https://github.com/wikimedia/restbase/blob/master/config.example.yaml

services:
  - name: restbase
    module: hyperswitch
    conf:
      port: 7231
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      ui_name: RESTBase
      ui_url: https://www.mediawiki.org/wiki/RESTBase
      ui_title: RESTBase docs
      spec:
        x-request-filters:
          - path: lib/security_response_header_filter.js
          - path: lib/normalize_headers_filter.js
        x-sub-request-filters:
          - type: default
            name: http
            options:
              allow:
                - pattern: http://http/api.php
                  forward_headers: true
                - pattern: http://parsoid:8000
                  forward_headers: true
                - pattern: /^https?:\/\//
        paths:
          /{domain:femiwiki.com}/{api:v1}:
            x-modules:
              - spec:
                  info:
                    version: 1.0.0
                    title: Wikimedia REST API
                    description: Welcome to your RESTBase API.
                  x-route-filters:
                    - path: ./lib/normalize_title_filter.js
                      options:
                        redirect_cache_control: 's-maxage=0, max-age=86400'
                  paths:
                    /page:
                      x-modules:
                        - path: v1/content.yaml
                          options:
                            response_cache_control: 's-maxage=0, max-age=86400'
                        - path: v1/common_schemas.yaml # Doesn't really matter where to mount it.
                    /transform:
                      x-modules:
                        - path: v1/transform.yaml

          /{domain:femiwiki.com}/{api:sys}:
            x-modules:
              - path: projects/proxy.yaml
                options:
                  backend_host_template: '{{"/{domain}/sys/legacy"}}'
              - spec:
                  paths:
                    /table:
                      x-modules:
                        - path: sys/table.js
                          options:
                            conf:
                              backend: sqlite
                              dbname: db.sqlite3
                              pool_idle_timeout: 20000
                              retry_delay: 250
                              retry_limit: 10
                              show_sql: false
                              storage_groups:
                                - name: local
                                  domains: /./
                    /legacy/key_value:
                      x-modules:
                        - path: sys/key_value.js
                    /legacy/page_revisions:
                      x-modules:
                        - path: sys/page_revisions.js
                    /post_data:
                      x-modules:
                        - path: sys/post_data.js
                    /action:
                      x-modules:
                        - path: sys/action.js
                          options:
                            # XXX Check API URL!
                            apiUriTemplate: http://http/api.php
                            # XXX Check the base RESTBase URI
                            baseUriTemplate: "{{'http://{domain}:7231/{domain}/v1'}}"
                    /page_save:
                      x-modules:
                        - path: sys/page_save.js
                    /parsoid:
                      x-modules:
                        - path: sys/parsoid.js
                          options:
                            parsoidHost: http://parsoid:8000
                            response_cache_control: 's-maxage=0, max-age=86400'
```
</details>

**Comment by lens0021** [comment]
**[2020-01-10 21:00+0900]** `aws_instance.mediawiki`에서 `yum install -y strace` 실행
**[2020-01-12 11:00+0900]** 테스트 목적으로 t3a.nano 스팟 인스턴스 요청

**Comment by lens0021** [comment]
https://github.com/femiwiki/docker-restbase/blob/201f90a0abd39dc6646a3957c4d265988ca9cb25/config.yaml#L87
위 부분을
- :x: `http://test.femiwiki.com/api.php`로 바꾼 경우 → 같은 오류
- :heavy_check_mark: `https://test.femiwiki.com/api.php`로 바꾼 경우 → 정상 작동

- :x: Caddyfile에 ` *:80`을 추가한 경우 → 같은 오류

오류가 난 경우 https://github.com/wikimedia/restbase/blob/e579be9c44677f090d6a9fed9f95618db608da5e/sys/action.js#L307 의 `res.body`는 html 형식이었으며 다음 내용이 포함되어 있었습니다: `A POST request was made without a "Content-Type" header. This does not work reliably.`

**Comment by lens0021** [comment]
스팟인스턴스 터미네이트하고 Route53 레코드도 지웠습니다.

**Comment by lens0021** [comment]
쿠버네티스 이전 전까지만 `MEDIAWIKI_APIS_URI`를 지정하는 것으로 일단 해결하기로 하고 아래 내용은 지웠습니다.

> [2020-01-08T05:00+0900] secret.php에 다음 추가하여 RESTBase 비활성함:
> 
> ```
> $wgVisualEditorAllowLossySwitching = true;
> unset( $wgVirtualRestConfig['modules']['restbase'] );
> $wgVisualEditorRestbaseURL = false;
> $wgVisualEditorFullRestbaseURL = false;
> ```

**Comment by lens0021** [comment]
Nomad에서도 똑같아서 확인이 더 필요해보입니다.

**Comment by lens0021** [comment]
RESTBase가 제거되어서 이 이슈도 닫습니다.
