### ISSUE TITLE
RESTBase: HTTPError: 404: not_found#route

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#153]
일단 편집에 눈에 뜨이는 문제는 없으나 RESTBase 사용 시마다 로그로 다음이 출력됩니다.
```json
{
  "name": "restbase",
  "hostname": "31292f66751f",
  "pid": 28,
  "level": 40,
  "err": {
    "message": "404: not_found#route",
    "name": "restbase",
    "stack": "HTTPError: 404: not_found#route\n    at HyperSwitch._request (/srv/restbase/node_modules/hyperswitch/lib/hyperswitch.js:268:19)\n    at _createFilteredHandler (/srv/restbase/node_modules/hyperswitch/lib/hyperswitch.js:170:26)\n    at tryCatcher (/srv/restbase/node_modules/bluebird/js/release/util.js:16:23)\n    at /srv/restbase/node_modules/bluebird/js/release/method.js:15:34\n    at handlerWrapper (/srv/restbase/node_modules/hyperswitch/lib/hyperswitch.js:422:37)\n    at next (/srv/restbase/node_modules/hyperswitch/lib/hyperswitch.js:408:42)\n    at Object.module.exports [as filter] (/srv/restbase/node_modules/hyperswitch/lib/filters/http.js:24:16)\n    at handlerWrapper (/srv/restbase/node_modules/hyperswitch/lib/hyperswitch.js:420:27)\n    at /srv/restbase/node_modules/hyperswitch/lib/hyperswitch.js:426:28\n    at HyperSwitch._filteredRequest (/srv/restbase/node_modules/hyperswitch/lib/hyperswitch.js:171:19)\n    at HyperSwitch.(anonymous function) [as post] (/srv/restbase/node_modules/hyperswitch/lib/hyperswitch.js:460:21)\n    at mwUtil.getSiteInfo.then (/srv/restbase/node_modules/restbase/sys/parsoid.js:88:22)\n    at tryCatcher (/srv/restbase/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/srv/restbase/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/srv/restbase/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/srv/restbase/node_modules/bluebird/js/release/promise.js:649:10)",
    "status": 404,
    "body": {
      "type": "not_found#route",
      "title": "Not found.",
      "internalURI": "/femiwiki.com/sys/events/",
      "method": "post",
      "depth": 2
    },
    "root_req": {
      "method": "get",
      "uri": "/femiwiki.com/v1/page/html/%ED%97%AC%EB%A0%8C_%EC%BC%88%EB%9F%AC?redirect=false&stash=true",
      "headers": {
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
        "api-user-agent": "VisualEditor-MediaWiki/1.34.0",
        "x-client-ip": "::ffff:10.0.15.2",
        "x-forwarded-for": "10.255.0.2, ::ffff:10.0.15.2",
        "x-request-id": "06a0ae10-3579-11ea-98b0-c1e0db3004ce",
        "x-request-class": "internal"
      }
    },
    "request_id": "06a0ae10-3579-11ea-98b0-c1e0db3004ce",
    "api_path": "/femiwiki.com/v1/page/html/{title}",
    "levelPath": "warn/bg-updates"
  },
  "msg": "404: not_found#route",
  "time": "2020-01-12T20:20:51.166Z",
  "v": 0
}
```

#### References

- https://phabricator.wikimedia.org/T129041

**Comment by lens0021** [comment]
이제 RESTBase를 쓰지 않습니다.
