### ISSUE TITLE
간헐적 로그인 불가 현상이 있음

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#250]
```
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Interface 'MediaWiki\Cache\Hook\BacklinkCacheGetConditionsHook' not found in /srv/femiwiki.com/includes/HookContainer/HookRunner.php:22
Stack trace:
#0 /srv/femiwiki.com/includes/AutoLoader.php(109): require()
#1 [internal function]: AutoLoader::autoload('MediaWiki\\HookC...')
#2 /srv/femiwiki.com/includes/MediaWikiServices.php(194): spl_autoload_call('MediaWiki\\HookC...')
#3 /srv/femiwiki.com/includes/config/ConfigFactory.php(52): MediaWiki\MediaWikiServices::getInstance()
#4 /srv/femiwiki.com/extensions/EmbedVideo/EmbedVideo.hooks.php(74): ConfigFactory::getDefaultInstance()
#5 /srv/femiwiki.com/includes/registration/ExtensionRegistry.php(543): EmbedVideoHooks::onExtension(Array)
#6 /srv/femiwiki.com/includes/registration/ExtensionRegistry.php(234): ExtensionRegistry->exportExtractedData(Array)
#7 /srv/femiwiki.com/includes/Setup.php(161): ExtensionRegistry->loadFromQueue()
#8 /srv/femiwiki.com/includes/WebStart.php(89): require_once('/srv/femiwiki.c...')
#9 /srv/femiwiki.com/index.php(44): in /srv/femiwiki.com/includes/HookContainer/HookRunner.php on line 22
[24-Apr-2021 20:44:02] ERROR: fork() failed: Cannot allocate memory (12)
127.0.0.1 -  24/Apr/2021:20:44:02 +0900 "GET /index.php" 500
[24-Apr-2021 20:44:02] WARNING: [pool www] child 414 exited on signal 9 (SIGKILL) after 16.058567 seconds from start
[24-Apr-2021 20:44:02] NOTICE: [pool www] child 437 started
```

로그인 시도 시 실패하고 서버에서는 위와 같은 로그가 출력됩니다
fastcgi 컨테이너를 재시작하면서 괜찮아졌는데 5회 이상 다시 발생하였습니다.

현재 환경은
- t3a에서 fastcgi(php-fpm), http(caddy), memcached 실행 중
- t4g에서 mysql 실행 중

**Comment by lens0021** [comment]
로그인 실패 때마다 journalctl에 다음이 나오는 걸 확인했습니다.

> Memory cgroup out of memory: Kill process 14109 (php-fpm) score 749 or sacrifice child
> kernel: Killed process 14109 (php-fpm) total-vm:400728kB, anon-rss:78976kB, file-rss:9620kB, shmem-rss:64532kB

**Comment by lens0021** [comment]
#249 와 원인이 같은 것 같아 이 이슈 닫습니다.
Duplicate of #249

**Comment by lens0021** [comment]
Duplicate of #249
