### ISSUE TITLE
Cannot propose an owner-only consumer with OAuth2.0

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#294]
> [6f06581fa7e7b5e726531dce] 2021-12-23 05:48:27: 종류 "Lcobucci\JWT\Signer\Key\FileCouldNotBeRead"에서 심각한 오류

```
[7e021bfc66d0289282e0c628] /w/%ED%8A%B9%EC%88%98:OAuth%EC%BB%A8%EC%8A%88%EB%A8%B8%EB%93%B1%EB%A1%9D/propose Lcobucci\JWT\Signer\Key\FileCouldNotBeRead: The path "" does not contain a valid key file

Backtrace:

from /srv/femiwiki.com/extensions/OAuth/vendor/lcobucci/jwt/src/Signer/Key/FileCouldNotBeRead.php(14)
#0 /srv/femiwiki.com/extensions/OAuth/vendor/lcobucci/jwt/src/Signer/Key/LocalFileReference.php(35): Lcobucci\JWT\Signer\Key\FileCouldNotBeRead::onPath(string)
#1 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/Entities/Traits/AccessTokenTrait.php(50): Lcobucci\JWT\Signer\Key\LocalFileReference::file(string, string)
#2 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/Entities/Traits/AccessTokenTrait.php(62): MediaWiki\Extensions\OAuth\Entity\AccessTokenEntity->initJwtConfiguration()
#3 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/Entities/Traits/AccessTokenTrait.php(91): MediaWiki\Extensions\OAuth\Entity\AccessTokenEntity->convertToJWT()
#4 /srv/femiwiki.com/extensions/OAuth/src/Frontend/SpecialPages/SpecialMWOAuthConsumerRegistration.php(321): MediaWiki\Extensions\OAuth\Entity\AccessTokenEntity->__toString()
#5 /srv/femiwiki.com/includes/specialpage/SpecialPage.php(647): MediaWiki\Extensions\OAuth\Frontend\SpecialPages\SpecialMWOAuthConsumerRegistration->execute(string)
#6 /srv/femiwiki.com/includes/specialpage/SpecialPageFactory.php(1366): SpecialPage->run(string)
#7 /srv/femiwiki.com/includes/MediaWiki.php(314): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#8 /srv/femiwiki.com/includes/MediaWiki.php(930): MediaWiki->performRequest()
#9 /srv/femiwiki.com/includes/MediaWiki.php(564): MediaWiki->main()
#10 /srv/femiwiki.com/index.php(53): MediaWiki->run()
#11 /srv/femiwiki.com/index.php(46): wfIndexMain()
#12 {main}
```

Setting `$wgOAuth2PrivateKey` will resolve this issue, but $wgOAuth2PrivateKey is not documented as required and the error message is not helpful.

| Variable name	| Default value |	Description |
|-|-|-|
|$wgOAuth2PrivateKey	|""|	Private key or a path to the private key used to sign OAuth2 JWT being transmitted.|
|$wgOAuth2PublicKey	|""|	Public key or a path to the public key used to verify OAuth2 resource requests.|

https://www.mediawiki.org/wiki/Extension:OAuth

**Comment by lens0021** [comment]
https://oauth2.thephpleague.com/installation/
이거 따라서 생성 하면 되려나 하고 있습니다.

**Comment by lens0021** [comment]
생성해 봤는데 성공해서 닫습니다.

https://femiwiki.com/w/%ED%8A%B9%EC%88%98:OAuth%EC%BB%A8%EC%8A%88%EB%A8%B8%EB%AA%A9%EB%A1%9D/view/c6384a9dcbf820df9a9a831a18e865d6
