### ISSUE TITLE
Authorization: Bearer 사용시 Fatal exception 발생

### ISSUE THREAD

**Issue by saschanaz** [femiwiki/femiwiki#305]
```
MediaWiki internal error.<br />
<br />
Original exception: [b0af31f1c47657f38a3e8cfd] 2022-05-06 07:33:02: Fatal exception of type &quot;ParseError&quot;<br />
<br />
Exception caught inside exception handler.<br />
<br />
Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information.<br />
```

헤더로 `Authorization: Bearer`를 넣으면 이런 오류가 발생하네요. Bearer 뒤에 토큰이 있어도 없어도 일단 Bearer로 시작하기만 하면 오류가 발생합니다. 혹시 확인 가능할까요?

확인한 경로는 `https://femiwiki.com/rest.php/v1/page/페미위키` 입니다.

```js
var res = await fetch("https://femiwiki.com/rest.php/v1/page/페미위키", { headers: { Authorization: "Bearer" } })
await res.text()
```

**Comment by saschanaz** [comment]
영문 위키피디아와 비교하면 이렇습니다.

```js
var res = await fetch("https://en.wikipedia.org/w/rest.php/v1/page/Earth", { headers: { Authorization: "Bearer" } })
await res.text()

// "{\"error\":\"rest-read-denied\",\"httpCode\":403,\"httpReason\":\"Forbidden\"}"
```

경로에 `w/`가 있고 없고의 차이도 있네요.

**Comment by saschanaz** [comment]
Action API도 똑같은 Fatal exception이 발생합니다.:

```js
var res = await fetch("https://femiwiki.com/w/api.php?action=login&format=json", { headers: { Authorization: "Bearer" } })
await res.text()

// "MediaWiki internal error.<br />
// <br />
// Original exception: [317d0d16eb28a78fefcd8be8] 2022-05-08 12:07:41: Fatal exception of type &quot;ParseError&quot;<br />
// <br />
// Exception caught inside exception handler.<br />
// <br />
// Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information.<br />
//
// " 
```

위키피디아:

```js
var res = await fetch("https://en.wikipedia.org/w/api.php?action=login&format=json", { headers: { Authorization: "Bearer" } })
await res.text()

// "{\"error\":{\"code\":\"mwoauth-invalid-authorization\",\"info\":\"The authorization headers in your request are not valid: Invalid access token\",\"*\":\"See https://en.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.\"},\"servedby\":\"mw1392\"}" 
```

**Comment by lens0021** [comment]
https://github.com/femiwiki/docker-mediawiki 를 실행하고 다음을 실행해서 오류를 확인해봤습니다.
```bash
curl 'http://127.0.0.1:8080/api.php?action=login&format=json' -X POST -H 'Authorization: Bearer'
```

아래와 같은 에러가 발생하는데,

> /api.php?action=login&amp;format=json   ParseError: syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)

<details>
<summary>full log</summary>

```
MediaWiki internal error.<br />
<br />
Original exception: [dea624e72eac83394bc7a88f] /api.php?action=login&amp;format=json   ParseError: syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)<br />
Backtrace:<br />
from /srv/femiwiki.com/extensions/OAuth/vendor/lcobucci/clock/src/SystemClock.php(13)<br />
#0 /srv/femiwiki.com/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile(string)<br />
#1 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(string)<br />
#2 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(80): spl_autoload_call(string)<br />
#3 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(66): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator-&gt;initJwtConfiguration()<br />
#4 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/ResourceServer.php(67): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator-&gt;setPublicKey(League\OAuth2\Server\CryptKey)<br />
#5 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/ResourceServer.php(84): League\OAuth2\Server\ResourceServer-&gt;getAuthorizationValidator()<br />
#6 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/Middleware/ResourceServerMiddleware.php(43): League\OAuth2\Server\ResourceServer-&gt;validateAuthenticatedRequest(GuzzleHttp\Psr7\ServerRequest)<br />
#7 /srv/femiwiki.com/extensions/OAuth/src/ResourceServer.php(89): League\OAuth2\Server\Middleware\ResourceServerMiddleware-&gt;__invoke(GuzzleHttp\Psr7\ServerRequest, MediaWiki\Extensions\OAuth\Response, Closure)<br />
#8 /srv/femiwiki.com/extensions/OAuth/src/SessionProvider.php(266): MediaWiki\Extensions\OAuth\ResourceServer-&gt;verify(GuzzleHttp\Psr7\ServerRequest, MediaWiki\Extensions\OAuth\Response, Closure)<br />
#9 /srv/femiwiki.com/extensions/OAuth/src/SessionProvider.php(101): MediaWiki\Extensions\OAuth\SessionProvider-&gt;verifyOAuth2Request(MediaWiki\Extensions\OAuth\ResourceServer, GuzzleHttp\Psr7\ServerRequest)<br />
#10 /srv/femiwiki.com/includes/session/SessionManager.php(525): MediaWiki\Extensions\OAuth\SessionProvider-&gt;provideSessionInfo(WebRequest)<br />
#11 /srv/femiwiki.com/includes/session/SessionManager.php(248): MediaWiki\Session\SessionManager-&gt;getSessionInfoForRequest(WebRequest)<br />
#12 /srv/femiwiki.com/includes/WebRequest.php(830): MediaWiki\Session\SessionManager-&gt;getSessionForRequest(WebRequest)<br />
#13 /srv/femiwiki.com/includes/session/SessionManager.php(169): WebRequest-&gt;getSession()<br />
#14 /srv/femiwiki.com/includes/Setup.php(770): MediaWiki\Session\SessionManager::getGlobalSession()<br />
#15 /srv/femiwiki.com/includes/WebStart.php(90): require_once(string)<br />
#16 /srv/femiwiki.com/api.php(43): require(string)<br />
#17 {main}<br />
<br />
Exception caught inside exception handler: [dea624e72eac83394bc7a88f] /api.php?action=login&amp;format=json   ParseError: syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)<br />
Backtrace:<br />
from /srv/femiwiki.com/extensions/OAuth/vendor/lcobucci/clock/src/SystemClock.php(13)<br />
#0 /srv/femiwiki.com/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile(string)<br />
#1 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(string)<br />
#2 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(80): spl_autoload_call(string)<br />
#3 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(66): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator-&gt;initJwtConfiguration()<br />
#4 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/ResourceServer.php(67): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator-&gt;setPublicKey(League\OAuth2\Server\CryptKey)<br />
#5 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/ResourceServer.php(84): League\OAuth2\Server\ResourceServer-&gt;getAuthorizationValidator()<br />
#6 /srv/femiwiki.com/extensions/OAuth/vendor/league/oauth2-server/src/Middleware/ResourceServerMiddleware.php(43): League\OAuth2\Server\ResourceServer-&gt;validateAuthenticatedRequest(GuzzleHttp\Psr7\ServerRequest)<br />
#7 /srv/femiwiki.com/extensions/OAuth/src/ResourceServer.php(89): League\OAuth2\Server\Middleware\ResourceServerMiddleware-&gt;__invoke(GuzzleHttp\Psr7\ServerRequest, MediaWiki\Extensions\OAuth\Response, Closure)<br />
#8 /srv/femiwiki.com/extensions/OAuth/src/SessionProvider.php(266): MediaWiki\Extensions\OAuth\ResourceServer-&gt;verify(GuzzleHttp\Psr7\ServerRequest, MediaWiki\Extensions\OAuth\Response, Closure)<br />
#9 /srv/femiwiki.com/extensions/OAuth/src/SessionProvider.php(101): MediaWiki\Extensions\OAuth\SessionProvider-&gt;verifyOAuth2Request(MediaWiki\Extensions\OAuth\ResourceServer, GuzzleHttp\Psr7\ServerRequest)<br />
#10 /srv/femiwiki.com/includes/session/SessionManager.php(525): MediaWiki\Extensions\OAuth\SessionProvider-&gt;provideSessionInfo(WebRequest)<br />
#11 /srv/femiwiki.com/includes/session/SessionManager.php(248): MediaWiki\Session\SessionManager-&gt;getSessionInfoForRequest(WebRequest)<br />
#12 /srv/femiwiki.com/includes/WebRequest.php(830): MediaWiki\Session\SessionManager-&gt;getSessionForRequest(WebRequest)<br />
#13 /srv/femiwiki.com/includes/user/User.php(1213): WebRequest-&gt;getSession()<br />
#14 /srv/femiwiki.com/includes/user/User.php(396): User-&gt;loadDefaults()<br />
#15 /srv/femiwiki.com/includes/user/User.php(2096): User-&gt;load()<br />
#16 /srv/femiwiki.com/includes/user/User.php(2966): User-&gt;getId()<br />
#17 /srv/femiwiki.com/includes/user/UserOptionsManager.php(645): User-&gt;isRegistered()<br />
#18 /srv/femiwiki.com/includes/user/UserOptionsManager.php(493): MediaWiki\User\UserOptionsManager-&gt;getCacheKey(User)<br />
#19 /srv/femiwiki.com/includes/user/UserOptionsManager.php(141): MediaWiki\User\UserOptionsManager-&gt;loadUserOptions(User, integer)<br />
#20 /srv/femiwiki.com/includes/user/User.php(2561): MediaWiki\User\UserOptionsManager-&gt;getOption(User, string, NULL, boolean)<br />
#21 /srv/femiwiki.com/includes/context/RequestContext.php(384): User-&gt;getOption(string)<br />
#22 /srv/femiwiki.com/includes/language/Message.php(381): RequestContext-&gt;getLanguage()<br />
#23 /srv/femiwiki.com/includes/language/Message.php(1395): Message-&gt;getLanguage()<br />
#24 /srv/femiwiki.com/includes/language/Message.php(919): Message-&gt;fetchMessage()<br />
#25 /srv/femiwiki.com/includes/language/Message.php(1009): Message-&gt;format(string)<br />
#26 /srv/femiwiki.com/includes/exception/MWExceptionRenderer.php(226): Message-&gt;text()<br />
#27 /srv/femiwiki.com/includes/exception/MWExceptionRenderer.php(161): MWExceptionRenderer::msg(string, string)<br />
#28 /srv/femiwiki.com/includes/exception/MWExceptionRenderer.php(77): MWExceptionRenderer::reportHTML(ParseError)<br />
#29 /srv/femiwiki.com/includes/exception/MWExceptionHandler.php(107): MWExceptionRenderer::output(ParseError, integer)<br />
#30 /srv/femiwiki.com/includes/exception/MWExceptionHandler.php(202): MWExceptionHandler::report(ParseError)<br />
#31 /srv/femiwiki.com/includes/exception/MWExceptionHandler.php(170): MWExceptionHandler::handleException(ParseError, string)<br />
#32 [internal function]: MWExceptionHandler::handleUncaughtException(ParseError)<br />
#33 {main}<br />
```

</details>

(https://github.com/wikimedia/mediawiki-extensions-OAuth 에는 composer.lock 파일이 없어서 확실하게는 파악하지 못했으나) lcobucci/clock 2.1.0 코드에서 에러가 난 부분은 PHP 8.0의 [Constructor property promotion](https://www.php.net/releases/8.0/en.php#constructor-property-promotion) 문법입니다.

```php
// https://github.com/lcobucci/clock/blob/903513d28e85376a33385ebc601afd2ee69e5653/src/SystemClock.php#L13
// …
final class SystemClock implements Clock
{
    public function __construct(private DateTimeZone $timezone)
    {
    }

    // …
}
```

아무래도 `composer update`를 실행했던 [composer:2.3.5 도커 이미지](https://hub.docker.com/_/composer)가 [PHP 8을 쓰고 있어서](https://github.com/composer/docker/blob/96587783bae9383640388da5718354dbf013ffd3/2.3/Dockerfile#L1) 문제가 생긴 것 같으며, [리드미에 써있는 방법](https://github.com/composer/docker/blob/96587783bae9383640388da5718354dbf013ffd3/2.3/Dockerfile#L1) 중 하나로 해결을 해봐야 할 것 같습니다.

**Comment by lens0021** [comment]
저희 Dockerfile을 살펴봤는데 확장 기능에 대해서는 다운받은 그대로 사용하고 별도로 Composer를 사용하지는 않네요, https://www.mediawiki.org/wiki/Special:ExtensionDistributor/OAuth 에서 다운받은 vendor에서도 php 8.0 코드를 확인할 수 있어 업스트림 문제 같습니다.

**Comment by lens0021** [comment]
https://phabricator.wikimedia.org/T307864 태스크를 작성했습니다.

**Comment by saschanaz** [comment]
감사합니다! 다른 문제지만 혹시 페미위키에서 PHP 8로 업그레이드가 불가한 다른 문제가 있나요?

**Comment by lens0021** [comment]
이유는 MediaWiki 1.37, 1.38, 1.39.0-wmf.10까지 아직 PHP 8.0을 지원하고 있지 않기 때문입니다! ([칸반](https://phabricator.wikimedia.org/project/view/4652/)) 퍼포먼스 문제도 있어서 지원만 되면 바로 8.0으로 갈아타고 싶은 마음은 굴뚝같습니다 :sob:

**Comment by lens0021** [comment]
[[1]](https://gerrit.wikimedia.org/r/c/789954)을 체리픽[[2]](https://github.com/femiwiki/mediawiki-extensions-OAuth/commit/4757dcc965c2963e9be8fd23bd809999a6a93fcf)하여 적용했습니다. 혹시 개선되었는지 알 수 있을까요? @saschanaz

**Comment by saschanaz** [comment]
여전히 같은 오류가 발생합니다.

페미위키 대문에서 개발자 툴을 열고 https://github.com/femiwiki/femiwiki/issues/305#issue-1227522065 의 코드를 붙여넣으면 테스트할 수 있습니다.

**Comment by saschanaz** [comment]
아, 자세히 보니 더이상 ParseError가 아니네요. 토큰을 제대로 주고 다시 테스트해 보겠습니다

```
MediaWiki internal error.<br />
<br />
Original exception: [7a8ca1575554226474d5e684] 2022-07-10 23:06:31: Fatal exception of type &quot;Error&quot;<br />
<br />
Exception caught inside exception handler.<br />
<br />
Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information.<br />
```

**Comment by saschanaz** [comment]
토큰이 있어도 같은 오류가 발생하네요 🥲

혹시 도움이 될만한 로그가 남았을까요?

**Comment by lens0021** [comment]
이 이슈 상황 혹시 아시나요?

**Comment by saschanaz** [comment]
두 API 모두 더이상 Fatal exception이 발생하지 않습니다. 다만 Actions API의 경우 영문 위키피디아와 같은 mwoauth-invalid-authorization 오류가 발생하도록 되었으나 REST API의 경우 페미위키에서는 rest-read-denied 오류가 발생합니다.

제대로 된 토큰으로 테스트해보려 했으나 기존 토큰이 expired되었는지 진행이 되질 않네요. 특수:OAuth컨슈머등록/update에서 '비밀 키를 새 값으로 재설정' 해서 새 토큰을 받으려는 경우 #294 와 같은 오류가 발생합니다. 아예 새 consumer를 만들려고 해도 #294 가 재발하네요 😬

**Comment by saschanaz** [comment]
지금은 Fatal exception도 없고 기존에 발급받았던 토큰을 사용해 테스트해본 결과 응답도 정상적으로 돌아옵니다. 따라서 닫습니다, 감사합니다!
