### ISSUE TITLE
update.php fails

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#309]
> ...
...echo_notification_user_hash_timestamp key doesn't exist.
...echo_push_provider table already exists.
...echo_push_topic table already exists.
...echo_push_subscription table already exists.
...echo_unread_wikis table does not exist, skipping modify field patch.
...flaggedimages doesn't exist.
...flaggedrevs table already exists.
...index fr_user already set on flaggedrevs table.
error following logs: invalid character 'i' in literal false (expecting 'l')

TBD

**Comment by lens0021** [comment]
> Table flaggedtemplates contains ft_title field. Dropping...Wikimedia\Rdbms\DBQueryError from line 1606 of /srv/femiwiki.com/includes/libs/rdbms/database/Database.php: Error 1062: Duplicate entry '187691-0' for key 'flaggedtemplates.PRIMARY' (mysql)
> Function: Wikimedia\Rdbms\Database::sourceFile( /srv/femiwiki.com/extensions/FlaggedRevs/backend/schema/mysql/patch-flaggedtemplates-fr_title.sql )
> Query: ALTER TABLE \`flaggedtemplates\`
>>  DROP PRIMARY KEY,
>>  ADD PRIMARY KEY (ft_rev_id, ft_tmp_rev_id),
>>  DROP COLUMN ft_title,
>>  DROP COLUMN ft_namespace

```
#0 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1590): Wikimedia\Rdbms\Database->getQueryException('Duplicate entry...', 1062, 'ALTER TABLE `fl...', 'Wikimedia\\Rdbms...')
#1 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1564): Wikimedia\Rdbms\Database->getQueryExceptionAndLog('Duplicate entry...', 1062, 'ALTER TABLE `fl...', 'Wikimedia\\Rdbms...')
#2 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1173): Wikimedia\Rdbms\Database->reportQueryError('Duplicate entry...', 1062, 'ALTER TABLE `fl...', 'Wikimedia\\Rdbms...', false)
#3 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(4954): Wikimedia\Rdbms\Database->query('ALTER TABLE `fl...', 'Wikimedia\\Rdbms...')
#4 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(4889): Wikimedia\Rdbms\Database->sourceStream(Resource id #2398, NULL, NULL, 'Wikimedia\\Rdbms...', NULL)
#5 /srv/femiwiki.com/includes/libs/rdbms/database/DBConnRef.php(69): Wikimedia\Rdbms\Database->sourceFile('/srv/femiwiki.c...')
#6 /srv/femiwiki.com/includes/libs/rdbms/database/MaintainableDBConnRef.php(35): Wikimedia\Rdbms\DBConnRef->__call('sourceFile', Array)
#7 /srv/femiwiki.com/includes/installer/DatabaseUpdater.php(704): Wikimedia\Rdbms\MaintainableDBConnRef->sourceFile('/srv/femiwiki.c...')
#8 /srv/femiwiki.com/includes/installer/DatabaseUpdater.php(862): DatabaseUpdater->applyPatch('/srv/femiwiki.c...', true, 'Table flaggedte...')
#9 /srv/femiwiki.com/includes/installer/DatabaseUpdater.php(533): DatabaseUpdater->dropField('flaggedtemplate...', 'ft_title', '/srv/femiwiki.c...', true)
#10 /srv/femiwiki.com/includes/installer/DatabaseUpdater.php(501): DatabaseUpdater->runUpdates(Array, true)
#11 /srv/femiwiki.com/maintenance/update.php(193): DatabaseUpdater->doUpdates(Array)
#12 /srv/femiwiki.com/maintenance/doMaintenance.php(114): UpdateMediaWiki->execute()
#13 /srv/femiwiki.com/maintenance/update.php(264): require_once('/srv/femiwiki.c...')
#14 {main}
```

**Comment by lens0021** [comment]
https://phabricator.wikimedia.org/T312708 filed.

**Comment by lens0021** [comment]
이런 쿼리를 생각해봤는데요, 테스트 서버를 띄워서 실험해봐야 좋을 것 같습니다.

```sql
UPDATE flaggedtemplates
  LEFT JOIN page ON
    flaggedtemplates.ft_namespace = page.page_namespace &&
    flaggedtemplates.ft_title = page.page_title
  SET flaggedtemplates.ft_tmp_rev_id = page.page_latest
  WHERE flaggedtemplates.ft_tmp_rev_id = 0;
```

**Comment by lens0021** [comment]
`php extensions/FlaggedRevs/maintenance/pruneRevData.php --rev-num=5 --prune`도 실행하고 위 쿼리도 실행한 후 update.php 했을 때 성공했습니다.
