### ISSUE TITLE
시각편집기 시작 실패

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#340]
![image](https://github.com/femiwiki/femiwiki/assets/28209361/2d15c12a-ca2a-4bd0-95fb-e3e197091f07)

RESTBase 로그 (`nomad alloc logs -f -n 10 c358c6e2`):
```
{
  "name": "restbase",
  "hostname": "ip-172-31-28-31.ap-northeast-1.compute.internal",
  "pid": 1,
  "level": 50,
  "message": "500: http_error",
  "res": {
    "name": "HTTPError",
    "message": "500: http_error",
    "status": 500,
    "headers": {
      "content-type": "text/html; charset=UTF-8",
      "server": "ip-172-31-28-31.ap-northeast-1.compute.internal",
      "status": "500 Internal Server Error",
      "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
      "x-content-type-options": "nosniff",
      "x-frame-options": "SAMEORIGIN",
      "x-powered-by": "PHP/8.1.13",
      "x-request-id": "da873760-ff4e-11ed-b665-9d51f9c90c98",
      "x-xss-protection": "1; mode=block",
      "date": "Wed, 31 May 2023 01:02:46 GMT",
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "GET,HEAD",
      "access-control-allow-headers": "accept, content-type, content-length, cache-control, accept-language, api-user-agent, if-match, if-modified-since, if-none-match, dnt, accept-encoding",
      "access-control-expose-headers": "etag",
      "referrer-policy": "origin-when-cross-origin",
      "content-security-policy": "default-src 'none'; media-src *; img-src *; style-src http://femiwiki.com https://femiwiki.com 'unsafe-inline';frame-ancestors 'self'",
      "x-content-security-policy": "default-src 'none'; media-src *; img-src *; style-src http://femiwiki.com https://femiwiki.com 'unsafe-inline';frame-ancestors 'self'",
      "x-webkit-csp": "default-src 'none'; media-src *; img-src *; style-src http://femiwiki.com https://femiwiki.com 'unsafe-inline';frame-ancestors 'self'",
      "cache-control": "private, max-age=0, s-maxage=0, must-revalidate"
    },
    "body": {
      "internalURI": "http://127.0.0.1:80/rest.php/femiwiki.com/v3/page/pagebundle/%ED%95%9C%EC%88%98%EB%AF%BC/187432",
      "internalMethod": "get"
    },
    "requestName": "get_from_backend"
  },
  "stack": "HTTPError: 500: http_error\n    at request.then (/srv/restbase/node_modules/preq/index.js:228:23)\n    at tryCatcher (/srv/restbase/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/srv/restbase/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/srv/restbase/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/srv/restbase/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/srv/restbase/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/srv/restbase/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/srv/restbase/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/srv/restbase/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/srv/restbase/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
  "latency": 979,
  "root_req": {
    "method": "get",
    "uri": "/femiwiki.com/v1/page/html/%ED%95%9C%EC%88%98%EB%AF%BC",
    "headers": {
      "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
      "x-client-ip": "::ffff:127.0.0.1",
      "x-forwarded-for": "123.254.254.53, ::ffff:127.0.0.1",
      "x-request-id": "da873760-ff4e-11ed-b665-9d51f9c90c98",
      "x-request-class": "internal"
    }
  },
  "request_id": "da873760-ff4e-11ed-b665-9d51f9c90c98",
  "levelPath": "error/request",
  "msg": "500: http_error",
  "time": "2023-05-31T01:02:46.697Z",
  "v": 0
}

```
`.stack`
```
HTTPError: 500: http_error
    at request.then (/srv/restbase/node_modules/preq/index.js:228:23)
    at tryCatcher (/srv/restbase/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/restbase/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/srv/restbase/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/srv/restbase/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/srv/restbase/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/srv/restbase/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/srv/restbase/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/srv/restbase/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/srv/restbase/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

fastcgi, http, restbase의 alloc들을 재시작 하였으나 효과 없음

**Comment by lens0021** [comment]
https://github.com/femiwiki/nomad/tree/09481bf9d400721423a16f60038736d011989b90 으로 롤백하였는데 괜찮은 상태

**Comment by lens0021** [comment]
ghcr.io/femiwiki/mediawiki:2023-04-15T01-52-d0d563ab과 ghcr.io/femiwiki/mediawiki:2023-04-22T16-57-a1a04a6f 사이에는 composer vendor, i18n 업데이트 등의 차이가 있고, VisualEditor에는 특별한 차이는 못 발견

**Comment by lens0021** [comment]
https://phabricator.wikimedia.org/T333993 도 관련 가능성 있음

**Comment by lens0021** [comment]
RESTBase is removed at https://github.com/femiwiki/docker-mediawiki/pull/776
