### ISSUE TITLE
MWTocWidget Uncaught TypeError

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#356]
```
ve.ui.MWTocWidget.js:45 Uncaught TypeError: Cannot read properties of undefined (reading 'connect')
    at new VeUiMWTocWidget (ve.ui.MWTocWidget.js:45:16)
    at ve.init.mw.DesktopArticleTarget.surfaceReady (ve.init.mw.DesktopAr…cleTarget.js:753:25)
    at ve.init.mw.Target.js:410:10
```

**Comment by lens0021** [comment]
https://phabricator.wikimedia.org/T355944
