### ISSUE TITLE
이메일 전송 실패

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#63]
https://github.com/femiwiki/skin/issues/81 이슈를 해결했음에도 불구하고 다음 메시지와 함께 이메일 전송이 실패합니다. 다음 두 가지 중 하나의 에러가 발생합니다.

첫 번째: 

> 504 Gateway Time-out

두 번째: 
> MediaWiki internal error.
>
>Original exception: [ec1d8acf1e13128d7278775f] 2019-03-19 14:25:15: Fatal exception of type "MWException"
>
>Exception caught inside exception handler.
>
>Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information.

위 안내에 따라 자세한 예외를 열람하면 다음과 같았습니다.

```
MediaWiki internal error.

Original exception: [ea2b34b0cd0dcce5c52c114e] /w/%ED%8A%B9%EC%88%98:%EC%9D%B4%EB%A9%94%EC%9D%BC%ED%99%95%EC%9D%B8 MWException from line 4238 of /srv/femiwiki.com/includes/user/User.php: CAS update failed on user_touched. The version of the user to be saved is older than the current version.
Backtrace:
#0 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(3805): User->{closure}(Wikimedia\Rdbms\DatabaseMysqli, string)
#1 /srv/femiwiki.com/includes/user/User.php(4251): Wikimedia\Rdbms\Database->doAtomicSection(string, Closure)
#2 /srv/femiwiki.com/includes/user/User.php(4693): User->saveSettings()
#3 /srv/femiwiki.com/includes/specials/SpecialConfirmemail.php(134): User->sendConfirmationMail()
#4 /srv/femiwiki.com/includes/htmlform/HTMLForm.php(665): EmailConfirmation->submitSend(array, OOUIHTMLForm)
#5 /srv/femiwiki.com/includes/htmlform/HTMLForm.php(557): HTMLForm->trySubmit()
#6 /srv/femiwiki.com/includes/htmlform/HTMLForm.php(572): HTMLForm->tryAuthorizedSubmit()
#7 /srv/femiwiki.com/includes/specials/SpecialConfirmemail.php(107): HTMLForm->show()
#8 /srv/femiwiki.com/includes/specials/SpecialConfirmemail.php(67): EmailConfirmation->showRequestForm()
#9 /srv/femiwiki.com/includes/specialpage/SpecialPage.php(569): EmailConfirmation->execute(NULL)
#10 /srv/femiwiki.com/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#11 /srv/femiwiki.com/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#12 /srv/femiwiki.com/includes/MediaWiki.php(860): MediaWiki->performRequest()
#13 /srv/femiwiki.com/includes/MediaWiki.php(517): MediaWiki->main()
#14 /srv/femiwiki.com/index.php(42): MediaWiki->run()
#15 {main}

Exception caught inside exception handler: [ea2b34b0cd0dcce5c52c114e] /w/%ED%8A%B9%EC%88%98:%EC%9D%B4%EB%A9%94%EC%9D%BC%ED%99%95%EC%9D%B8 Wikimedia\Rdbms\DBTransactionStateError from line 1341 of /srv/femiwiki.com/includes/libs/rdbms/database/Database.php: Cannot execute query from PageImages::getPageImage while transaction status is ERROR.
Backtrace:
#0 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1127): Wikimedia\Rdbms\Database->assertTransactionStatus(string, string)
#1 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1693): Wikimedia\Rdbms\Database->query(string, string)
#2 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1518): Wikimedia\Rdbms\Database->select(string, array, array, string, array, array)
#3 /srv/femiwiki.com/extensions/PageImages/includes/PageImages.php(58): Wikimedia\Rdbms\Database->selectField(string, array, array, string, array)
#4 /srv/femiwiki.com/extensions/PageImages/includes/PageImages.php(199): PageImages::getPageImage(Title)
#5 /srv/femiwiki.com/includes/Hooks.php(174): PageImages::onBeforePageDisplay(OutputPage, SkinFemiwiki)
#6 /srv/femiwiki.com/includes/Hooks.php(234): Hooks::callHook(string, array, array, NULL, string)
#7 /srv/femiwiki.com/includes/OutputPage.php(2703): Hooks::runWithoutAbort(string, array)
#8 /srv/femiwiki.com/includes/exception/MWException.php(181): OutputPage->output()
#9 /srv/femiwiki.com/includes/exception/MWException.php(222): MWException->reportHTML()
#10 /srv/femiwiki.com/includes/exception/MWExceptionHandler.php(96): MWException->report()
#11 /srv/femiwiki.com/includes/exception/MWExceptionHandler.php(172): MWExceptionHandler::report(MWException)
#12 /srv/femiwiki.com/includes/MediaWiki.php(544): MWExceptionHandler::handleException(MWException)
#13 /srv/femiwiki.com/index.php(42): MediaWiki->run()
#14 {main}
```

https://github.com/wikimedia/mediawiki/blob/d727e8b3a0dd39109fc5e339bfa1a147a469c946/includes/user/User.php#L4238-L4240

**Comment by lens0021** [comment]
로드밸런서 타임아웃 때문일 수도 있을 것 같아서 EC2 인스턴스의 퍼블릭 DNS에서 메일 보내기를 시도해봤습니다.

`<h1>`으로 나오던 "504 Gateway Time-out"가 보통 글자 `504 Gateway Timeout`로 나오는 변화가 있었습니다.

**Comment by lens0021** [comment]
https://www.mediawiki.org/wiki/Manual:How_to_debug#Logging 에 따라 secret.php에 `$wgDebugTimestamps = true; $wgDebugLogFile = "/var/log/mediawiki/debug-{$wgDBname}.log";`를 추가한 뒤, 제 계정에서 사용자:낙엽 봇으로 이메일 보내기를 시도하면서 로그를 찍어서 찾아봤습니다, 다음 로그가 관련이 있어보입니다.

```
0.3423   6.0M  UserMailer::send: sending mail to =?UTF-8?Q?=EB=82=99=EC=97=BD=20=EB=B4=87?= <************@gmail.com>
0.3427   6.0M  Sending mail via PEAR::Mail
...
60.4042   6.0M  PEAR::Mail failed: Failed to connect to email-smtp.us-east-1.amazonaws.com:25 [SMTP: Failed to connect socket: Connection timed out (code: -1, response: )]
```
- `%EB%82%99%EC%97%BD%20%EB%B4%87`는 `낙엽 봇`입니다, 제 이메일은 로그에서 가렸습니다.
- 각 라인 첫 번째 숫자는 `microtime( true ) - $_SERVER['REQUEST_TIME_FLOAT']`이고 두 번째 숫자는 `memory_get_usage( true ) / ( 1024 * 1024 )`입니다. ([코드](https://github.com/wikimedia/mediawiki/blob/d727e8b3a0dd39109fc5e339bfa1a147a469c946/includes/GlobalFunctions.php#L998-L1008))

**Comment by lens0021** [comment]
특이한 점은 현재도 메일이 보내질 때도 있고 안 보내질 때도 있다는 것입니다. 메일 개수 제한은 많이 남아있고(24시간 제한의 경우 지금 확인해보면 49984개가 남았습니다), 또, 다른 서버(예: 제 노트북)에서는 재현이 안 되는 걸 보면 IP에 따른 제한이 있는지도 모르겠습니다..

**Comment by lens0021** [comment]
[Amazon SES와 관련된 SMTP 연결 또는 시간 초과 문제를 해결하려면 어떻게 해야 합니까?](https://aws.amazon.com/ko/premiumsupport/knowledge-center/smtp-connectivity-timeout-issues-ses/)

**Comment by lens0021** [comment]
> **참고**: 기본적으로 Amazon EC2는 모든 인스턴스에 대해 SMTP 포트 25에서 트래픽을 조정합니다. SMTP 포트 25를 사용해도 시간 초과 오류가 계속 발생할 경우, 조정을 제거하도록 요청하거나, 전송에 사용된 포트(예: 587)를 변경할 수 있습니다. 자세한 내용은 EC2 인스턴스에서 포트 25의 제한을 제거할 수 있습니까? 단원을 참조하십시오.
> -https://aws.amazon.com/ko/premiumsupport/knowledge-center/smtp-connectivity-timeout-issues-ses/

에 따라 587로 바꾸는 것으로 합니다~

**Comment by lens0021** [comment]
다음 배포까지 기다리기 좀 그래서 서버에서도 바로 수정했습니다~
